LibararyManagement/Areas/Librarian/Controllers/LibrarianController.cs
using LibararyManagement.Areas.Librarian.Repository;
using LibararyManagement.Filter;
using LibararyManagement.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibararyManagement.Areas.Librarian.Controllers
{
    [Authentication]
    public class LibrarianController : Controller
    {
        private readonly ILibrarian _librarian;

        public LibrarianController(ILibrarian librarian)
        {
            _librarian = librarian;
        }
        // GET: Librarian/Librarian
        public ActionResult Index(int page = 1)
        {
            List<Pagination_Result> books = _librarian.getAllBooks(page);
            if (page != 1)
            {
                ViewBag.PreviousPage = page - 1;
            }
            if (books.Count < 3)
            {
                ViewBag.nextPagenum = page;
            }
            else
            {
                ViewBag.nextPagenum = page + 1;
            }
            ViewBag.pagenum = page;
            return View(books);
        }
        [HttpGet]
        public ActionResult AddBook()
        {
            return View();
        }
        [HttpPost]
        public bool AddBook(Book book)
        {
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase profile = Request.Files[0];

            string ImageName = profile.FileName;
            var path = Path.Combine(Server.MapPath("/Images/"), ImageName);
            book.BookCoverPage = ImageName;
            _librarian.addBook(book);
            profile.SaveAs(path);
            return true;
        }
        [HttpGet]
        public ActionResult EditBook(int id)
        {
            GetEditBook_Result model = _librarian.EditBook(id);
            return View(model);
        }
        [HttpPost]
        public bool EditBook(Book book)
        {
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase profile = Request.Files[0];

            string ImageName = profile.FileName;
            var path = Path.Combine(Server.MapPath("/Images/"), ImageName);
            book.BookCoverPage = ImageName;
            _librarian.EditBook(book);
            profile.SaveAs(path);
            return true;
        }
        [HttpGet]
        public ActionResult GetDeleteBook(int Id)
        {
            GetEditBook_Result model = _librarian.GetDeleteBook(Id);
            return View(model);
        }
        [HttpPost]
        public bool DeleteBook(int Id)
        {
            _librarian.DeleteBook(Id);
            return true;
        }
        public JsonResult getReaderData()
        {
            List<getReader_Result> list = _librarian.getReaderData();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public bool BookIssue(int BookId, DateTime IssueDate, int UserId, int status, DateTime ExpectedReturnDate)
        {
            _librarian.BookIssue(BookId, IssueDate, UserId, status, ExpectedReturnDate);
            return true;
        }
        [HttpPost]
        public bool returnBookDate(int BookId, DateTime ReturnDate)
        {
            _librarian.returnBookDate(BookId, ReturnDate);
            return true;
        }
        public ActionResult allAvailbleBook(int page = 1)
        {
            List<getAllAvailbleBook_Result> books = _librarian.getAllAvailbleBooks(page);
            if (page != 1)
            {
                ViewBag.PreviousPage = page - 1;
            }
            if (books.Count < 3)
            {
                ViewBag.nextPagenum = page;
            }
            else
            {
                ViewBag.nextPagenum = page + 1;
            }
            ViewBag.pagenum = page;
            return View(books);
        }
        public ActionResult allIsuueBook(int page = 1)
        {
            List<getAllIssueBook_Result> books = _librarian.getAllIssueBooks(page);
            if (page != 1)
            {
                ViewBag.PreviousPage = page - 1;
            }
            if (books.Count < 3)
            {
                ViewBag.nextPagenum = page;
            }
            else
            {
                ViewBag.nextPagenum = page + 1;
            }
            ViewBag.pagenum = page;
            return View(books);
        }
        public ActionResult historyOfIssueBook(int page = 1)
        {
            List<getAllIssueBookHistory_Result> books = _librarian.getAllHistoryIssueBooks(page);
            if (page != 1)
            {
                ViewBag.PreviousPage = page - 1;
            }
            if (books.Count < 3)
            {
                ViewBag.nextPagenum = page;
            }
            else
            {
                ViewBag.nextPagenum = page + 1;
            }
            ViewBag.pagenum = page;
            return View(books);
        }
        [HttpGet]
        public ActionResult blockUser()
        {
            List<getAllUser_Result> list = _librarian.blockUser();
            return View(list);
        }
        [HttpPost]
        public bool blockUser(int Id)
        {
            _librarian.blockUser(Id);
            return true;
        }
        [HttpPost]
        public bool unBlock(int Id)
        {
            _librarian.unBlock(Id);
            return true;
        }

    }
}

LibararyManagement/Areas/Librarian/Views/Librarian/AddBook.cshtml
@{
    ViewBag.Title = "AddBook";
}

<h2>AddBook</h2>

<section>
    <div>
        <div>
            <div>
                <div>
                    <label class="m-2" style="width:150px">Book Name</label>
                    <input type="text" id="bookName" />
                </div>
                <div>
                    <label class="m-2" style="width: 150px; margin: 10px">Author</label>
                    <input type="text" id="Author" />
                </div>
            </div>
            <div>
                <div>
                    <label class="m-2" style="width: 150px; margin: 10px">Subject</label>
                    <select id="Subject">
                        <option value="">Please Select Subject</option>
                        <option value="Religious">Religious</option>
                        <option value="Science">Science</option>
                        <option value="Biology">Biology</option>
                        <option value="Reserch">Reserch</option>
                        <option value="Biography">Biography</option>
                    </select>
                </div>
            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width: 150px; margin: 10px">Book Cover Page</label>
                <input type="file" accept="image/jpg,image/png,image/jpeg" id="CoverPhoto" />
            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width: 150px; margin: 10px">Language</label>
                <select id="Language">
                    <option value="">Please Select Language</option>
                    <option value="English">English</option>
                    <option value="Hindi">Hindi</option>
                </select>
            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width: 150px; margin: 10px">Page</label>
                <input type="number" id="NumberOfPage" />
            </div>
        </div>
        <div>
            <button onclick="submit()" class="btn btn-outline-primary margin:10px">Create</button>
        </div>
    </div>
</section>

@section scripts{
    <script>
        function submit() {
            var formData = new FormData();
            var files = $("#CoverPhoto").get(0).files;
            formData.append("files", files[0])
            formData.append("BookName", $("#bookName").val())
            formData.append("Author", $("#Author").val())
            formData.append("Subject", $("#Subject").val())
            formData.append("Language", $("#Language").val())
            formData.append("Page", $("#NumberOfPage").val())
            $.ajax({
                type: 'POST',
                url: "@Url.Action("AddBook")",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    location.href = "@Url.Action("Index")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
    </script>
}

LibararyManagement/Areas/Librarian/Views/Librarian/EditBook.cshtml
@{
    ViewBag.Title = "EditBook";
}
@model LibararyManagement.Models.GetEditBook_Result
<h2>EditBook</h2>

<section>
    <div>
        <div>
            <div>
                <div>
                    <label class="m-2" style="width:150px">Book Name</label>
                    <input type="text" id="bookName" value="@Model.BookName" />
                </div>
                <div>
                    <label class="m-2" style="width:150px">Author</label>
                    <input type="text" id="Author" value="@Model.Author" />
                </div>
            </div>
            <div>
                <div>
                    <label class="m-2" style="width:150px">Subject</label>
                    @if (String.Equals(Model.Subject, "Religious"))
                    {
                        <select id="Subject">
                            <option value="">Please Select Subject</option>
                            <option selected value="Religious">Religious</option>
                            <option value="Science">Science</option>
                            <option value="Biology">Biology</option>
                            <option value="Reserch">Reserch</option>
                            <option value="Biography">Biography</option>
                        </select>
                    }
                    @if (String.Equals(Model.Subject, "Science"))
                    {
                        <select id="Subject">
                            <option value="">Please Select Subject</option>
                            <option value="Religious">Religious</option>
                            <option selected value="Science">Science</option>
                            <option value="Biology">Biology</option>
                            <option value="Reserch">Reserch</option>
                            <option value="Biography">Biography</option>
                        </select>
                    }
                    @if (String.Equals(Model.Subject, "Biology"))
                    {
                        <select id="Subject">
                            <option value="">Please Select Subject</option>
                            <option value="Religious">Religious</option>
                            <option value="Science">Science</option>
                            <option selected value="Biology">Biology</option>
                            <option value="Reserch">Reserch</option>
                            <option value="Biography">Biography</option>
                        </select>
                    }
                    @if (String.Equals(Model.Subject, "Reserch"))
                    {
                        <select id="Subject">
                            <option value="">Please Select Subject</option>
                            <option value="Religious">Religious</option>
                            <option value="Science">Science</option>
                            <option value="Biology">Biology</option>
                            <option selected value="Reserch">Reserch</option>
                            <option value="Biography">Biography</option>
                        </select>
                    }
                    @if (String.Equals(Model.Subject, "Biography"))
                    {
                        <select id="Subject">
                            <option value="">Please Select Subject</option>
                            <option value="Religious">Religious</option>
                            <option value="Science">Science</option>
                            <option value="Biology">Biology</option>
                            <option value="Reserch">Reserch</option>
                            <option selected value="Biography">Biography</option>
                        </select>
                    }
                </div>
            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width:150px">Book Cover Page</label>
                <input type="file" accept="image/jpg,image/png,image/jpeg" id="CoverPhoto" value="F:\Dot Net\Mvc\Libarary Management\LibararyManagement\LibararyManagement\Images\@Model.BookCoverPage" />
            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width:150px">Language</label>
                @if (String.Equals(Model.Language, "English"))
                {
                    <select id="Language">
                        <option value="">Please Select Language</option>
                        <option selected value="English">English</option>
                        <option value="Hindi">Hindi</option>
                    </select>
                }
                @if (String.Equals(Model.Language, "Hindi"))
                {
                    <select id="Language">
                        <option value="">Please Select Language</option>
                        <option value="English">English</option>
                        <option selected value="Hindi">Hindi</option>
                    </select>
                }


            </div>
        </div>
        <div>
            <div>
                <label class="m-2" style="width:150px">Page</label>
                <input type="number" id="Page" value="@Model.Page" />
            </div>
        </div>
        <div>
            <button onclick="Update(this.value)" class="btn btn-outline-primary m-2" value="@Model.BookId">Update</button>
        </div>
    </div>
</section>

@section scripts{

    <script>
        function Update(Id) {
            var formData = new FormData();
            var files = $("#CoverPhoto").get(0).files;
            formData.append("files", files[0])
            formData.append("BookName", $("#bookName").val())
            formData.append("Author", $("#Author").val())
            formData.append("Subject", $("#Subject").val())
            formData.append("Language", $("#Language").val())
            formData.append("Page", $("#Page").val())
            formData.append("BookId", Id)
            $.ajax({
                type: "POST",
                url: '@Url.Action("EditBook")',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (response) {
                    location.href = "@Url.Action("Index")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }

            })
        }
    </script>
}

LibararyManagement/Areas/Librarian/Views/Librarian/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model List<LibararyManagement.Models.Pagination_Result>

<div class="d-flex justify-content-between mb-2">
    <h2 class="m-0">Book Details</h2>
    @Html.ActionLink("Add book", "Addbook", "librarian", new { area = "librarian" }, new { @class = "btn btn-outline-dark" })
</div>

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-sm-4 mt-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" style="height:200px" src="~/Images/@item.BookCoverPage" alt="Card image cap">
                <div class="card-body">
                    <h5 class="m-0">@item.BookName</h5>
                    <div class="d-flex mt-2">
                        <p class="m-0" style="font-weight:500;font-size:14px"><span style="color:Highlight">Subject : </span>@item.Subject</p>
                        <p class="m-0" style="font-size:14px;font-weight:500"><span style="color:Highlight;margin-left:10px">By : </span>@item.Author</p>
                    </div>
                    <p class="m-0" style="font-size:14px;font-weight:500;"><span style="color:Highlight;">Language : </span>@item.Language</p>
                    <p class="m-0" style="font-size:14px;font-weight:500;"><span style="color:Highlight;">Total Page : </span>@item.Page</p>
                    <div class="d-flex mt-2">
                        @if (item.Status == null || item.Status == 1 || item.Status == 2)
                        {
                            <button class="btn btn-primary m-1" onclick="getReader(@item.BookId)">Book Issue</button>
                        }
                        else
                        {
                            <button class="btn btn-primary m-1" onclick="getReturnDateDiv(@item.BookId)">Return</button>
                        }
                        @Html.ActionLink("Edit", "EditBook", "librarian",new { area = "librarian" ,id = item.BookId}, new { @class = "btn btn-secondary m-1" })
                        @Html.ActionLink("Delete", "GetDeleteBook", "librarian", new { area = "librarian" , Id = item.BookId }, new { @class = "btn btn-danger m-1" })
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="position-absolute d-none border" style="top:50%;left:50%;transform:translate(-50%,-50%);background-color:white;width:280px" id="BookIssueDiv">
        <div class="p-3">
            <div class="mb-3">
                <label class="m-0">Please Select Student</label><br />
                <select id="select">
                </select>
            </div>
            <div>
                <label>Issue Date Is :</label>
                <input type="date" id="date" disabled />
                <input type="date" id="ExpectedReturnDate" hidden />
            </div>
        </div>
        <div style="padding-left:16px;padding-bottom:16px">
            <button class="btn btn-secondary" onclick="Issue(this.value)" id="IssueBtn">Issue</button>
            <button onclick="cancelIssueDiv()" class="btn btn-danger">Cancel</button>
        </div>
    </div>
    <div class="position-absolute d-none border" style="top:50%;left:50%;transform:translate(-50%,-50%);background-color:white;width:280px" id="BookReturnDiv">
        <div class="d-flex justify-content-center align-items-center flex-column p-3">
            <div>
                <label>Return Date Is :</label>
                <input type="date" id="Returndate" />
            </div>
        </div>
        <div style="padding-left:16px;padding-bottom:16px">
            <button class="btn btn-secondary" onclick="AddReturnDate(this.value)" id="IssueReturnBtn">Return Book</button>
            <button onclick="CancelReturnDiv()" class="btn btn-danger">Cancel</button>
        </div>
    </div>
</div>

<ul class="pagination mt-3">
    <li class="page-item"><a href="@Url.Action("Index")?page=@ViewBag.PreviousPage" class="page-link" style="cursor:pointer">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">@ViewBag.pagenum</a></li>
    <li class="page-item"><a href="@Url.Action("Index")?page=@ViewBag.nextPagenum" class="page-link" style="cursor:pointer">Next</a></li>
</ul>

@section scripts{

    <script>
        function getReader(Id) {
            var today = new Date();
            var dd = today.getDate();
            var mm = today.getMonth() + 1; //January is 0!
            var yyyy = today.getFullYear();
            if (dd < 10) {
                dd = '0' + dd
            }
            if (mm < 10) {
                mm = '0' + mm
            }
            today = yyyy + '-' + mm + '-' + dd;
            $("#BookIssueDiv").removeClass('d-none');
            $("#select").empty();
            $.ajax({
                type: "GET",
                url: "@Url.Action("getReaderData","Librarian")",
                success: function (result) {
                    $("#date").val(today);
                    $("#IssueBtn").val(Id);
                    $.each(result, function (index, value) {
                        $("#select").append('<option value = ' + value.UserId + '>' + value.FirstName + ' ' + value.LastName + '</option>')
                    })
                    console.log(result)
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
        function cancelIssueDiv() {
            $("#BookIssueDiv").addClass('d-none');
        }
        function CancelReturnDiv() {
            $("#BookReturnDiv").addClass("d-none")
        }
        function Issue(Id) {
            var date = $("#date").val();
            let returnDates = new Date(date);
            var UserId = $("#select").val();
            returnDates.setDate(returnDates.getDate() + 5);
            if ((returnDates.getMonth() + 1) < 9) {
                var month = '0' + (returnDates.getMonth() + 1)
            }
            else {
                var month = (returnDates.getMonth() + 1)
            }
            if (returnDates.getDate() < 9) {
                var day = '0' + returnDates.getDate()
            }
            else {
                var day = returnDates.getDate()
            }

            let formatted_date = returnDates.getFullYear() + "-" + month + "-" + day;
            $("#ExpectedReturnDate").val(formatted_date);
            var returnDate = $("#ExpectedReturnDate").val();
            $.ajax({
                type: "POST",
                url: "@Url.Action("BookIssue")",
                data: {
                    "BookId": Id,
                    "IssueDate": date,
                    "UserId": UserId,
                    "status": '0', /*BookIssueStatus*/
                    "ExpectedReturnDate": returnDate
                },
                success: function (result) {
                    location.href = "@Url.Action("index")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
        function getReturnDateDiv(Id) {
            var today = new Date().toISOString().split('T')[0];
            $("#Returndate").attr('min', today)
            $("#BookReturnDiv").removeClass("d-none");
            $("#BookIssueDiv").addClass('d-none');
            $("#IssueReturnBtn").val(Id)
        }
        function AddReturnDate(BookId) {
            var ReturnDate = $("#Returndate").val();
            $.ajax({
                type: "POST",
                url: "@Url.Action("returnBookDate")",
                data: {
                    "BookId": BookId,
                    "ReturnDate": ReturnDate,
                },
                success: function () {
                    location.href = "@Url.Action("index")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
    </script>
}

LibararyManagement/Areas/Librarian/Views/Librarian/allAvailbleBook.cshtml
@{
    ViewBag.Title = "Index";
}
@model List<LibararyManagement.Models.getAllAvailbleBook_Result>

<div class="d-flex justify-content-between mb-2">
    <h2 class="m-0">Availble Book</h2>
</div>

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-sm-4 mt-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" style="height:200px" src="~/Images/@item.BookCoverPage" alt="Card image cap">
                <div class="card-body">
                    <h5 class="m-0">@item.BookName</h5>
                    <div class="d-flex mt-2">
                        <p class="m-0" style="font-weight:500;font-size:14px"><span style="color:Highlight">Subject : </span>@item.Subject</p>
                        <p class="m-0" style="font-size:14px;font-weight:500"><span style="color:Highlight;margin-left:10px">By : </span>@item.Author</p>
                    </div>
                    <p class="m-0" style="font-size:14px;font-weight:500;"><span style="color:Highlight;">Language : </span>@item.Language</p>
                    <p class="m-0" style="font-size:14px;font-weight:500;"><span style="color:Highlight;">Total Page : </span>@item.Page</p>
                    <div class="d-flex mt-2">
                        @if (item.Status == null || item.Status == 1 || item.Status == 2)
                        {
                            <button class="btn btn-primary m-1" onclick="getReader(@item.BookId)">Book Issue</button>
                        }
                        else
                        {
                            <button class="btn btn-primary m-1" onclick="getReturnDateDiv(@item.BookId)">Return</button>
                        }
                        @Html.ActionLink("Edit", "EditBook", "librarian", new { area = "librarian", id = item.BookId }, new { @class = "btn btn-secondary m-1" })
                        @Html.ActionLink("Delete", "GetDeleteBook", "librarian", new { area = "librarian", Id = item.BookId }, new { @class = "btn btn-danger m-1" })
                    </div>
                </div>
            </div>
        </div>
    }
    <div class="position-absolute d-none border" style="top:50%;left:50%;transform:translate(-50%,-50%);background-color:white;width:280px" id="BookIssueDiv">
        <div class="p-3">
            <div class="mb-3">
                <label class="m-0">Please Select Student</label><br />
                <select id="select">
                </select>
            </div>
            <div>
                <label>Issue Date Is :</label>
                <input type="date" id="date" disabled />
                <input type="date" id="ExpectedReturnDate" hidden />
            </div>
        </div>
        <div style="padding-left:16px;padding-bottom:16px">
            <button class="btn btn-secondary" onclick="Issue(this.value)" id="IssueBtn">Issue</button>
            <button onclick="cancelIssueDiv()" class="btn btn-danger">Cancel</button>
        </div>
    </div>

</div>

<ul class="pagination mt-3">
    <li class="page-item"><a href="@Url.Action("Index")?page=@ViewBag.PreviousPage" class="page-link" style="cursor:pointer">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">@ViewBag.pagenum</a></li>
    <li class="page-item"><a href="@Url.Action("Index")?page=@ViewBag.nextPagenum" class="page-link" style="cursor:pointer">Next</a></li>
</ul>

@section scripts{

    <script>
        function getReader(Id) {
            var today = new Date();
            var dd = today.getDate();
            var mm = today.getMonth() + 1; //January is 0!
            var yyyy = today.getFullYear();
            if (dd < 10) {
                dd = '0' + dd
            }
            if (mm < 10) {
                mm = '0' + mm
            }
            today = yyyy + '-' + mm + '-' + dd;
            $("#BookIssueDiv").removeClass('d-none');
            $("#select").empty();
            $.ajax({
                type: "GET",
                url: "@Url.Action("getReaderData","Librarian")",
                success: function (result) {
                    $("#date").val(today);
                    $("#IssueBtn").val(Id);
                    $.each(result, function (index, value) {
                        $("#select").append('<option value = ' + value.UserId + '>' + value.FirstName + ' ' + value.LastName + '</option>')
                    })
                    console.log(result)
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
        function cancelIssueDiv() {
            $("#BookIssueDiv").addClass('d-none');
        }
        function Issue(Id) {
            var date = $("#date").val();
            let returnDates = new Date(date);
            var UserId = $("#select").val();
            returnDates.setDate(returnDates.getDate() + 5);
            if ((returnDates.getMonth() + 1) < 9) {
                var month = '0' + (returnDates.getMonth() + 1)
            }
            else {
                var month = (returnDates.getMonth() + 1)
            }
            if (returnDates.getDate() < 9) {
                var day = '0' + returnDates.getDate()
            }
            else {
                var day = returnDates.getDate()
            }

            let formatted_date = returnDates.getFullYear() + "-" + month + "-" + day;
            $("#ExpectedReturnDate").val(formatted_date);
            var returnDate = $("#ExpectedReturnDate").val();
            $.ajax({
                type: "POST",
                url: "@Url.Action("BookIssue")",
                data: {
                    "BookId": Id,
                    "IssueDate": date,
                    "UserId": UserId,
                    "status": '0', /*BookIssueStatus*/
                    "ExpectedReturnDate": returnDate
                },
                success: function (result) {
                    location.href = "@Url.Action("index")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
    </script>
}

LibararyManagement/Areas/Librarian/Views/Librarian/blockUser.cshtml
@{
    ViewBag.Title = "User Management";
}
@model List<LibararyManagement.Models.getAllUser_Result>
<h2>Users</h2>

<table class="table">
    <tbody>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Address</th>
            <th>Action</th>
        </tr>
    </tbody>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.PhoneNumber</td>
                <td>@item.Email</td>
                <td>@item.Address</td>
                <td>
                    @if (item.IsActive == 0)
                    {
                        <button class="btn btn-primary" onclick="unBlockUser(this.value)" value="@item.UserId">Unblock</button>
                    }
                    else
                    {
                        <button class="btn btn-danger" onclick="blockUser(this.value)" value="@item.UserId">Block</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        function blockUser(Id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("blockUser")",
                data: { 'Id': Id },
                success: function () {
                    location.href = "@Url.Action("blockUser")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
        function unBlockUser(Id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("unBlock")",
                data: { 'Id': Id },
                success: function () {
                    location.href = "@Url.Action("blockUser")"
                },
                error: function () {
                    console.log("Somthing Went Wrong")
                }
            })
        }
    </script>
}